// lib/firebase_options.dart
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform;

// TODO: Replace with actual Firebase options generated by FlutterFire CLI
// Run: flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:165299750567:android:b5e759acd32e091494fd82',
    messagingSenderId: '165299750567',
    projectId: 'paw-aid-nyxie',
    storageBucket: 'paw-aid-nyxie.firebasestorage.app',
  );
}
